# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    app: coding-app
    version: 0.0.1
  name: coding-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coding-app
      version: 0.0.1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coding-app
        version: 0.0.1
      name: coding-app
    spec:
      containers:
      - image: coding:0.0.1
        imagePullPolicy: IfNotPresent
        name: coding-app
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
