# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    app: coding-app
    version: 0.0.1
  name: coding-app
  namespace: default
spec:
  ports:
  -
    protocol: TCP
    port: 9999
    protocol: TCP
    targetPort: 8080
  selector:
    app: coding-app
    version: 0.0.1
  sessionAffinity: None
  type: NodePort
